title: Dylan Meca
description: Soy Dylan Meca, científico e ingeniero informático y programador informático aficionado.
author:
  name: Dylan Meca
  email: 
show_downloads: false
google_analytics: G-588R86TJDG
comments: true
show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

  social_links:
    twitter: meca_dylan
    github: dylan14567
    youtube_channel: UCSUN3qthUfkVO2OwnJh3HQg
    instagram: dylanmeca

theme: minima

disqus:
  shortname: dylan14567

url: "https://dylan14567.github.io"

paginate: 10
paginate_path: "/blog/page:num/"

defaults:
    scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
