title: SUPERDYLANYT
description: Soy Dylan Alexander y un programador de videojuegos y aplicaciones y experto en inform√°tica.
author:
  name: dylan14567
  email: 
show_downloads: false
google_analytics: G-K77VC3PRR2
comments: true
show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

  social_links:
    twitter: DYLAN1456711
    github: dylan14567
    youtube_channel: UC-8PccwG6tE8kCvRJO3nIAw
    instagram: superdylanyt.oficial

theme: minima

disqus:
  shortname: true

plugins:
 - jekyll-feed
 - jekyll-seo-tag
