title: Dylan Meca
description: Soy Dylan Meca, un python developer ğŸ’» con experiencia en el desarrollo de herramientas de automatizaciÃ³n ğŸ¤–, especializado en temas de marketing ğŸ§‘â€ğŸ’¼ y arduino ğŸ› ï¸
author:
  name: Dylan Meca
  email: 
show_downloads: false
lang: es
google_analytics: G-J2H6BBV34K
comments: true
show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

  social_links:
    twitter: meca_dylan
    github: dylanmeca
    youtube: DylanMeca

theme: minima

disqus:
  shortname: dylan14567

url: "https://dylanmeca.github.io"
paginate: 10
paginate_path: "/page:num/"

defaults:
    scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false

header_pages:
  - about.md
  - contact.html
  - categories.html
  - search.html

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
