title: Dylan Meca
description: Soy Dylan Meca, un desarrollador de software ğŸ–¥ï¸ altamente capacitado en el lenguaje Python ğŸ. A lo largo de mi carrera, he demostrado dedicaciÃ³n y perseverancia en el mundo de la programaciÃ³n, y siempre estoy buscando nuevos desafÃ­os y oportunidades para mejorar mis habilidades y conocimientos. ğŸ“š
author:
  name: Dylan Meca
  email: 
show_downloads: false
lang: es
google_analytics: G-J2H6BBV34K
comments: true
show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

  social_links:
    twitter: meca_dylan
    github: dylanmeca
    youtube: DylanMeca

theme: minima

disqus:
  shortname: dylan14567

url: "https://dylanmeca.github.io"
paginate: 10
paginate_path: "/page:num/"

defaults:
    scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false

header_pages:
  - about.md
  - contact.html
  - categories.html
  - search.html

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
