title: DYLAN14567
description: Welcome
author:
  name: dylan14567
  email: 
show_downloads: false
google_analytics:
comments: true
show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

  social_links:
    twitter: DYLAN1456711
    github: dylan14567
    youtube_channel: UCXZow-eof6WFmu4armVahAA
    instagram: superdylanyt.oficial

theme: minima

disqus:
  shortname: true

plugins:
 - jekyll-feed
 - jekyll-seo-tag
